//! falcon-cascade — the control-cascade orchestrator component.
//!
//! Imports the five controller interfaces (`ekf`, `position`,
//! `attitude`, `rate`, `mixer`) and exports the top-level `step`.
//! `step` runs the cascade in order:
//!
//! ```text
//!   imu ─► ekf.estimate ─► state
//!   state, waypoint ─► position.tick ─► attitude-setpoint
//!   state, att-sp   ─► attitude.tick ─► rate-setpoint
//!   state, rate-sp  ─► rate.tick     ─► torque-setpoint
//!   torque-sp       ─► mixer.mix     ─► motor-pwm
//! ```
//!
//! The imports are satisfied by the five leaf components at
//! composition time — `wac plug` (or falcon-cascade.wac) wires the
//! graph. This component contains no control logic itself: it is
//! pure orchestration, which is the point of the Component Model
//! split — the cascade topology lives in one small, auditable place.

// Bindings generated by cargo-component as src/bindings.rs.
#[allow(warnings)]
mod bindings;

// The `cascade` world exports the `controller` interface; its Guest
// trait lives under `exports::`. The five imported controller
// interfaces live at the bindings root.
use bindings::exports::falcon::cascade::controller::Guest;
use bindings::falcon::cascade::{attitude, ekf, mixer, position, rate};
use bindings::falcon::cascade::types::{ImuSample, MotorPwm, Waypoint};

struct Component;

impl Guest for Component {
    fn step(imu: ImuSample, target: Waypoint) -> MotorPwm {
        // 1. State estimation.
        let state = ekf::estimate(imu);
        // 2. Outer position loop → attitude setpoint.
        let att_sp = position::tick(state, target);
        // 3. Attitude loop → rate setpoint.
        let rate_sp = attitude::tick(state, att_sp);
        // 4. Rate loop → torque setpoint.
        let torque = rate::tick(state, rate_sp);
        // 5. Control allocation → per-motor PWM.
        mixer::mix(torque)
    }
}

bindings::export!(Component with_types_in bindings);
