//! falcon-cascade — THE FLIGHT CORE, as one component.
//!
//! v0.8 rework. v0.7 imported five stage interfaces (`ekf`, `position`,
//! `attitude`, `rate`, `mixer`) and composed them with `wac plug`. That
//! decomposition was a wasm-side invention which never corresponded to the
//! flight architecture, and it drifted: the stages wrapped relay-pos/att/rate,
//! which falcon-core DROPPED on 2026-06-03 when it moved to geometric SE(3) +
//! ADRC. For three months and ~40 releases the published components implemented
//! a control stack the vehicle does not fly, and nothing noticed because nothing
//! compared the two dependency sets (#388).
//!
//! This component wraps `falcon_core::FlightCore` directly, so what is published
//! IS what is verified and flown: IEKF estimator, geometric SE(3) attitude, ADRC
//! inner loop, mixer with rotor-out FDI, and the altitude/position loops.
//!
//! It imports nothing. One component, one tick, one clock — which also removes
//! the other half of the defect: the five stages each advanced their own
//! hardcoded clock (20 ms, 4 ms, 1 ms) while the cascade called all five once
//! per tick, so they disagreed with each other by up to 20x.
//!
//! `FlightCore` drives a `FlightBackend` rather than returning motors, so the
//! component supplies a capture backend: the sensor frame goes in as the `read_*`
//! answers, and `write_motors` is caught on the way out.

#![cfg_attr(not(feature = "std"), no_std)]

// Bounded work-memory arena + `cabi_realloc` + panic handler from the shared
// crate (crates/falcon-cm-rt), so the unsafe lives in one audited place.
#[cfg(not(feature = "std"))]
falcon_cm_rt::export_cm_rt!();

// Bindings generated by cargo-component as src/bindings.rs.
#[allow(warnings)]
#[cfg(feature = "bazel-bindings")]
use falcon_cascade_bindings as bindings;
#[cfg(not(feature = "bazel-bindings"))]
mod bindings;

// The `cascade` world exports the `controller` interface; its Guest
// trait lives under `exports::`. The five imported controller
// interfaces live at the bindings root.
use bindings::exports::pulseengine::falcon_cascade::controller::Guest;
// The RETURN direction's Guest trait (SWREQ-FALCON-TRANSPORT-P01). A SECOND
// export, so an observer reads state without executing a control tick.
use bindings::exports::pulseengine::falcon_cascade::observer::Guest as ObserverGuest;
use bindings::pulseengine::falcon_cascade::types::{
    FlightState, MotorPwm, SensorFrame, VehicleConfig, Waypoint,
};

use core::cell::RefCell;
use falcon_core::{FlightBackend, FlightCore, ImuSample as CoreImu};

/// falcon-core's `Vec3` alias is private, so it is restated here. Same shape
/// (`[f32; 3]`, NED); if that ever diverges this stops compiling, which is the
/// right failure.
type Vec3 = [f32; 3];

struct SingleThreaded<T>(RefCell<T>);
// SAFETY: the component model guarantees single-threaded, non-reentrant access.
unsafe impl<T> Sync for SingleThreaded<T> {}

/// Lazily built: `FlightCore::new` needs the host's loop rate, which only
/// arrives with the first frame. Constructing it on a guessed rate is exactly
/// the defect v0.8 exists to remove.
static CORE: SingleThreaded<Option<FlightCore>> = SingleThreaded(RefCell::new(None));

/// THE PUBLISHED STATE, and a monotonic tick that never resets
/// (SWREQ-FALCON-TRANSPORT-P01). Written at the END of every `step`, read by
/// `observer.read-state` WITHOUT running a tick — the integrator's constraint
/// (jess#167): on the M4, observing must not execute the controller.
///
/// The tick is stored once and copied into BOTH `tick-head` and `tick-tail` on
/// read, so an in-process reader always sees a coherent pair. That is not
/// theatre for the cross-core case it exists for: when this state is placed in
/// shared OCRAM, the writer bumps head, writes the body, then bumps tail, and a
/// reader on the other core retries while they disagree. Publishing the same
/// value in both fields here keeps the CONTRACT honest for a single address
/// space while the layout is already correct for the split one.
static PUBLISHED: SingleThreaded<Option<PublishedState>> = SingleThreaded(RefCell::new(None));

/// What `step` latches for observers. Plain copy type — no allocation, no lock.
#[derive(Clone, Copy)]
struct PublishedState {
    tick: u32,
    q: [f32; 4],
    p: [f32; 3],
    v: [f32; 3],
    w: [f32; 3],
    bg: [f32; 3],
    innovation: f32,
    failed_rotor: u8,
    valid: u32,
}

/// `valid` bits. A CLEAR bit means NOT MEASURED — never "the value is zero".
/// Absence and zero arriving indistinguishably is the defect class this whole
/// release line keeps finding, so the seam refuses to conflate them.
const V_ATT: u32 = 1 << 0;
const V_POS: u32 = 1 << 1;
const V_VEL: u32 = 1 << 2;
const V_RATE: u32 = 1 << 3;
const V_BIAS: u32 = 1 << 4;
const V_INNOV: u32 = 1 << 5;
const V_ROTOR: u32 = 1 << 6;

/// The host's calibration, if it supplied one. `None` keeps the v0.8 defaults.
static CONFIG: SingleThreaded<Option<VehicleConfig>> = SingleThreaded(RefCell::new(None));

/// Sanitise one host-supplied number. A calibration arrives across an ABI from
/// code this component does not control, and `pos-var = 0` or a NaN gain does
/// not fail loudly — it quietly destroys the filter several seconds later. A
/// rejected value falls back to the built-in default, which is wrong for the
/// airframe but not divergent.
fn sane(v: f32, default: f32, positive: bool) -> f32 {
    if v.is_finite() && (!positive || v > 0.0) {
        v
    } else {
        default
    }
}

/// The two values that can only be supplied at CONSTRUCTION: hover thrust and
/// loop rate. Split out from the tuning below because `FlightCore` must be built
/// directly into its slot — see `apply_tuning`.
fn core_params(cfg: Option<&VehicleConfig>, frame_hz: f32) -> (f32, f32) {
    match cfg {
        // Unconfigured: byte-for-byte the v0.8 behaviour, so an existing host
        // that never calls `configure` sees no change whatsoever.
        None => (0.5, frame_hz),
        Some(c) => (
            sane(c.hover_thrust, 0.5, true),
            sane(c.loop_rate_hz, frame_hz, true),
        ),
    }
}

/// Apply the live-settable half of the calibration, IN PLACE.
///
/// This is deliberately not a `-> FlightCore` builder. A builder returns the
/// core by value through its own frame, and `FlightCore` is large (the IEKF
/// carries a full covariance matrix) while this component links a 8 KiB shadow
/// stack — a budget that is a shipped property, not an accident, because the
/// no-grow invariant is what lets jess lower the image to bare metal. The
/// by-value form overflowed that stack and trapped as an out-of-bounds access
/// inside `FlightCore::new`. Constructing into the slot and mutating through
/// `&mut` keeps exactly one core in memory at all times.
fn apply_tuning(core: &mut FlightCore, c: &VehicleConfig) {
    core.set_pos_var(sane(c.pos_var, 0.01, true));
    core.set_process_floor(
        sane(c.process_floor_vel, 0.0, false),
        sane(c.process_floor_pos, 0.0, false),
    );
    core.set_altitude_gains(
        sane(c.altitude_kp, 0.05, false),
        sane(c.altitude_kd, 0.30, false),
    );
    core.set_altitude_integral_gain(sane(c.altitude_ki, 0.0, false));
    // falcon-core's default ki_pos is 0.02, NOT zero — an unconfigured host must
    // keep it, and a rejected value must fall back to it rather than to 0.
    core.set_position_integral_gain(sane(c.position_ki, 0.02, false));
}

/// One tick's sensors in, motors out.
///
/// `FlightCore` pulls from a backend and pushes motors into it, which is the
/// seam that lets the SAME code run against SITL, Gazebo or real hardware. A
/// component has to answer with a value instead, so this stands in for one tick:
/// every `read_*` returns what the frame carried, and `write_motors` is caught.
///
/// Returning `None` where the frame carried nothing is the point — the core
/// then skips that fusion step rather than being handed a fabricated zero,
/// which would be silently wrong rather than merely absent.
struct FrameBackend {
    imu: CoreImu,
    position: Option<Vec3>,
    mag: Option<Vec3>,
    heading: Option<f32>,
    /// v0.10: per-rotor ESC telemetry. `None` leaves the rotor-out FDI on its
    /// RPM-free path, which is what every published component did until now.
    motor_rpm: Option<[i32; 4]>,
    dt: f32,
    motors: [f32; 4],
}

impl FlightBackend for FrameBackend {
    fn read_imu(&mut self) -> CoreImu {
        self.imu
    }
    fn read_position(&mut self) -> Option<Vec3> {
        self.position
    }
    fn read_mag(&mut self) -> Option<Vec3> {
        self.mag
    }
    fn read_heading(&mut self) -> Option<f32> {
        self.heading
    }
    fn read_motor_rpm(&mut self) -> Option<[i32; 4]> {
        self.motor_rpm
    }
    fn write_motors(&mut self, motors: &[f32]) {
        for (i, m) in self.motors.iter_mut().enumerate() {
            *m = motors.get(i).copied().unwrap_or(0.0);
        }
    }
    fn dt(&self) -> f32 {
        self.dt
    }
}

struct Component;

impl Guest for Component {
    fn step(sensors: SensorFrame, target: Waypoint) -> MotorPwm {
        #[cfg(not(feature = "std"))]
        falcon_cm_rt::BumpArena::reset();

        // The host's ACTUAL period. Clamped to [0.1 ms, 100 ms] so a garbage
        // frame cannot wind the filters; a non-finite value falls back to the
        // v0.7 constant, the only rate that was ever safe to assume.
        let dt = if sensors.dt_s.is_finite() {
            sensors.dt_s.clamp(0.0001, 0.1)
        } else {
            0.001
        };

        let imu = sensors.imu;
        let mut backend = FrameBackend {
            imu: CoreImu {
                accel: [imu.ax, imu.ay, imu.az],
                gyro: [imu.gx, imu.gy, imu.gz],
            },
            position: sensors.position_ned.map(|p| [p.x, p.y, p.z]),
            mag: sensors.mag_body.map(|m| [m.x, m.y, m.z]),
            heading: sensors.heading_rad,
            motor_rpm: sensors.motor_rpm.map(|r| [r.m1, r.m2, r.m3, r.m4]),
            dt,
            motors: [0.0; 4],
        };

        {
            let mut guard = CORE.0.borrow_mut();
            // Built from the host's calibration if `configure` was called, and
            // from the v0.8 defaults otherwise. The loop rate comes from the
            // calibration or from the frame — never from a constant.
            let cfg = CONFIG.0.borrow();
            let fresh = guard.is_none();
            let (hover, hz) = core_params(cfg.as_ref(), 1.0 / dt);
            // `get_or_insert_with` writes the core straight into the slot; the
            // tuning is then applied through `&mut`, never by value.
            let core = guard.get_or_insert_with(|| FlightCore::new(hover, hz));
            if fresh {
                if let Some(c) = cfg.as_ref() {
                    apply_tuning(core, c);
                }
            }
            core.set_position([target.north, target.east, target.down]);
            core.step(&mut backend);

            // LATCH FOR OBSERVERS, after the tick so the state corresponds to
            // the motors this call returns.
            let ns = core.state();
            let failed = core.failed_motor();
            let mut prev = PUBLISHED.0.borrow_mut();
            let tick = prev.as_ref().map(|s| s.tick.wrapping_add(1)).unwrap_or(0);
            // Every field below is produced by the core each tick, so all are
            // valid; `failed-rotor` is valid as a READING (0xFF = no fault),
            // which is distinct from "not measured".
            let valid = V_ATT | V_POS | V_VEL | V_RATE | V_BIAS | V_INNOV | V_ROTOR;
            *prev = Some(PublishedState {
                tick,
                q: ns.q,
                p: ns.p,
                v: ns.v,
                w: [imu.gx, imu.gy, imu.gz],
                bg: ns.b_g,
                innovation: 0.0,
                failed_rotor: failed.map(|i| i as u8).unwrap_or(0xFF),
                valid,
            });
        }

        MotorPwm {
            m1: backend.motors[0],
            m2: backend.motors[1],
            m3: backend.motors[2],
            m4: backend.motors[3],
        }
    }

    /// Install the calibration and DROP the existing core, so the next `step`
    /// rebuilds from it.
    ///
    /// Dropping is deliberate. `loop_rate_hz` is fixed at construction while
    /// every other knob is live-settable, so applying a late `configure` in
    /// place would silently honour eight fields and ignore the ninth. A host
    /// would then be flying a rate it did not ask for with no error of any
    /// kind — the same shape of defect as the hardcoded `dt` this seam was
    /// built to remove. An explicit re-initialisation is louder and cheaper.
    fn configure(cfg: VehicleConfig) {
        #[cfg(not(feature = "std"))]
        falcon_cm_rt::BumpArena::reset();

        *CONFIG.0.borrow_mut() = Some(cfg);
        *CORE.0.borrow_mut() = None;
    }
}

/// THE RETURN DIRECTION (SWREQ-FALCON-TRANSPORT-P01).
///
/// Reads the state `step` latched, WITHOUT running a control tick. Before this
/// existed the seam was `step(sensors, target) -> motor-pwm` and nothing else,
/// so the verified MAVLink telemetry stack (MAVLINK-P06, v1.119) had nothing to
/// read, no log could be written, and a shadow flight against a reference
/// filter produced no comparable evidence. Christof put it as "the cascade is
/// only a middle"; this is one half of the answer.
impl ObserverGuest for Component {
    fn read_state() -> FlightState {
        let s = PUBLISHED.0.borrow();
        match s.as_ref() {
            Some(p) => FlightState {
                // Same value in head and tail: an in-process reader cannot
                // observe a tear. The FIELDS are ordered for the cross-core
                // case (head first, tail last) so the layout is already right
                // when this lands in shared OCRAM.
                tick_head: p.tick,
                qw: p.q[0], qx: p.q[1], qy: p.q[2], qz: p.q[3],
                pos_n: p.p[0], pos_e: p.p[1], pos_d: p.p[2],
                vel_n: p.v[0], vel_e: p.v[1], vel_d: p.v[2],
                wx: p.w[0], wy: p.w[1], wz: p.w[2],
                bgx: p.bg[0], bgy: p.bg[1], bgz: p.bg[2],
                innovation: p.innovation,
                failed_rotor: p.failed_rotor,
                valid: p.valid,
                tick_tail: p.tick,
            },
            // NO TICK HAS RUN. Every field is zero and `valid` is 0, so a
            // reader sees "nothing measured" rather than a plausible-looking
            // level attitude at the origin. Returning zeros WITH the valid bits
            // set would be the absence-looks-like-data defect again.
            None => FlightState {
                tick_head: 0,
                qw: 1.0, qx: 0.0, qy: 0.0, qz: 0.0,
                pos_n: 0.0, pos_e: 0.0, pos_d: 0.0,
                vel_n: 0.0, vel_e: 0.0, vel_d: 0.0,
                wx: 0.0, wy: 0.0, wz: 0.0,
                bgx: 0.0, bgy: 0.0, bgz: 0.0,
                innovation: 0.0,
                failed_rotor: 0xFF,
                valid: 0,
                tick_tail: 0,
            },
        }
    }
}

bindings::export!(Component with_types_in bindings);
