// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod pulseengine {
        pub mod relay_stored_command {
            /// Stored Command — autonomous command sequencing with time tags.
            ///
            /// Manages Absolute Time Sequences (ATS) that fire at UTC timestamps,
            /// and Relative Time Sequences (RTS) that fire at offsets from start.
            ///
            /// P3 async: all functions are async fn — the host can call without blocking.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod stored_command {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// An absolute time sequence command.
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct AtsCommand {
                    pub execute_at_sec: u64,
                    pub command_code: u16,
                    pub payload_offset: u32,
                    pub payload_len: u32,
                    pub dispatched: bool,
                }
                impl ::core::fmt::Debug for AtsCommand {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("AtsCommand")
                            .field("execute-at-sec", &self.execute_at_sec)
                            .field("command-code", &self.command_code)
                            .field("payload-offset", &self.payload_offset)
                            .field("payload-len", &self.payload_len)
                            .field("dispatched", &self.dispatched)
                            .finish()
                    }
                }
                /// A dispatched command ready for execution.
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct DispatchedCommand {
                    pub command_code: u16,
                    pub payload_offset: u32,
                    pub payload_len: u32,
                }
                impl ::core::fmt::Debug for DispatchedCommand {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("DispatchedCommand")
                            .field("command-code", &self.command_code)
                            .field("payload-offset", &self.payload_offset)
                            .field("payload-len", &self.payload_len)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_init_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::init();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(_) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_init<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_load_ats_command_cabi<T: Guest>(
                    arg0: i64,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::load_ats_command(AtsCommand {
                        execute_at_sec: arg0 as u64,
                        command_code: arg1 as u16,
                        payload_offset: arg2 as u32,
                        payload_len: arg3 as u32,
                        dispatched: _rt::bool_lift(arg4 as u8),
                    });
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_start_rts_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i64,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::start_rts(arg0 as u32, arg1 as u64);
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_stop_rts_cabi<T: Guest>(arg0: i32) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::stop_rts(arg0 as u32);
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_process_tick_cabi<T: Guest>(arg0: i64) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::process_tick(arg0 as u64);
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_process_tick<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 12, 4);
                }
                pub trait Guest {
                    /// Initialize the stored command engine. Returns error string on failure.
                    fn init() -> Result<(), _rt::String>;
                    /// Load an ATS command. Returns false if table full.
                    fn load_ats_command(cmd: AtsCommand) -> bool;
                    /// Start a relative time sequence. Returns false if invalid or empty.
                    fn start_rts(rts_id: u32, current_time: u64) -> bool;
                    /// Stop a relative time sequence. Returns false if invalid ID.
                    fn stop_rts(rts_id: u32) -> bool;
                    /// Process one tick. Returns commands to dispatch this frame.
                    fn process_tick(current_time: u64) -> _rt::Vec<DispatchedCommand>;
                }
                #[doc(hidden)]
                macro_rules! __export_pulseengine_relay_stored_command_stored_command_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "pulseengine:relay-stored-command/stored-command@0.1.0#init")]
                        unsafe extern "C" fn export_init() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_init_cabi::<$ty > () } } #[unsafe
                        (export_name =
                        "cabi_post_pulseengine:relay-stored-command/stored-command@0.1.0#init")]
                        unsafe extern "C" fn _post_return_init(arg0 : * mut u8,) { unsafe
                        { $($path_to_types)*:: __post_return_init::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "pulseengine:relay-stored-command/stored-command@0.1.0#load-ats-command")]
                        unsafe extern "C" fn export_load_ats_command(arg0 : i64, arg1 :
                        i32, arg2 : i32, arg3 : i32, arg4 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_load_ats_command_cabi::<$ty > (arg0,
                        arg1, arg2, arg3, arg4) } } #[unsafe (export_name =
                        "pulseengine:relay-stored-command/stored-command@0.1.0#start-rts")]
                        unsafe extern "C" fn export_start_rts(arg0 : i32, arg1 : i64,) ->
                        i32 { unsafe { $($path_to_types)*:: _export_start_rts_cabi::<$ty
                        > (arg0, arg1) } } #[unsafe (export_name =
                        "pulseengine:relay-stored-command/stored-command@0.1.0#stop-rts")]
                        unsafe extern "C" fn export_stop_rts(arg0 : i32,) -> i32 { unsafe
                        { $($path_to_types)*:: _export_stop_rts_cabi::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "pulseengine:relay-stored-command/stored-command@0.1.0#process-tick")]
                        unsafe extern "C" fn export_process_tick(arg0 : i64,) -> * mut u8
                        { unsafe { $($path_to_types)*:: _export_process_tick_cabi::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "cabi_post_pulseengine:relay-stored-command/stored-command@0.1.0#process-tick")]
                        unsafe extern "C" fn _post_return_process_tick(arg0 : * mut u8,)
                        { unsafe { $($path_to_types)*:: __post_return_process_tick::<$ty
                        > (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_pulseengine_relay_stored_command_stored_command_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 3
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub use alloc_crate::vec::Vec;
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_relay_stored_command_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::pulseengine::relay_stored_command::stored_command::__export_pulseengine_relay_stored_command_stored_command_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::pulseengine::relay_stored_command::stored_command);
    };
}
#[doc(inline)]
pub(crate) use __export_relay_stored_command_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:pulseengine:relay-stored-command@0.1.0:relay-stored-command:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 587] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xc0\x03\x01A\x02\x01\
A\x02\x01B\x10\x01r\x05\x0eexecute-at-secw\x0ccommand-code{\x0epayload-offsety\x0b\
payload-leny\x0adispatched\x7f\x04\0\x0bats-command\x03\0\0\x01r\x03\x0ccommand-\
code{\x0epayload-offsety\x0bpayload-leny\x04\0\x12dispatched-command\x03\0\x02\x01\
j\0\x01s\x01@\0\0\x04\x04\0\x04init\x01\x05\x01@\x01\x03cmd\x01\0\x7f\x04\0\x10l\
oad-ats-command\x01\x06\x01@\x02\x06rts-idy\x0ccurrent-timew\0\x7f\x04\0\x09star\
t-rts\x01\x07\x01@\x01\x06rts-idy\0\x7f\x04\0\x08stop-rts\x01\x08\x01p\x03\x01@\x01\
\x0ccurrent-timew\0\x09\x04\0\x0cprocess-tick\x01\x0a\x04\05pulseengine:relay-st\
ored-command/stored-command@0.1.0\x05\0\x04\0;pulseengine:relay-stored-command/r\
elay-stored-command@0.1.0\x04\0\x0b\x1a\x01\0\x14relay-stored-command\x03\0\0\0G\
\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen\
-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
