// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod pulseengine {
        pub mod relay_scheduler {
            /// Scheduler — transforms time ticks into scheduled actions.
            ///
            /// The host calls tick() at each minor frame (typically 100Hz).
            /// The Scheduler reads its Schedule Definition Table and returns
            /// which actions to fire.
            ///
            /// P3 async: tick() is async fn — the host can call without blocking.
            /// On embedded (Gale): callback lifting mode, single stack.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod scheduler {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// A scheduled action to fire.
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct ScheduledAction {
                    pub target_channel: u32,
                    pub payload_offset: u32,
                    pub payload_len: u32,
                }
                impl ::core::fmt::Debug for ScheduledAction {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ScheduledAction")
                            .field("target-channel", &self.target_channel)
                            .field("payload-offset", &self.payload_offset)
                            .field("payload-len", &self.payload_len)
                            .finish()
                    }
                }
                /// A schedule slot configuration.
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct ScheduleSlot {
                    pub minor_frame: u32,
                    pub major_frame: u32,
                    pub target_channel: u32,
                    pub payload_offset: u32,
                    pub payload_len: u32,
                    pub enabled: bool,
                }
                impl ::core::fmt::Debug for ScheduleSlot {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("ScheduleSlot")
                            .field("minor-frame", &self.minor_frame)
                            .field("major-frame", &self.major_frame)
                            .field("target-channel", &self.target_channel)
                            .field("payload-offset", &self.payload_offset)
                            .field("payload-len", &self.payload_len)
                            .field("enabled", &self.enabled)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_init_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::init();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(_) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_init<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_tick_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::tick(arg0 as u32, arg1 as u32);
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_tick<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 12, 4);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_add_slot_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                    arg4: i32,
                    arg5: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::add_slot(ScheduleSlot {
                        minor_frame: arg0 as u32,
                        major_frame: arg1 as u32,
                        target_channel: arg2 as u32,
                        payload_offset: arg3 as u32,
                        payload_len: arg4 as u32,
                        enabled: _rt::bool_lift(arg5 as u8),
                    });
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_set_enabled_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::set_enabled(
                        arg0 as u32,
                        _rt::bool_lift(arg1 as u8),
                    );
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_slot_count_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::slot_count();
                    _rt::as_i32(result0)
                }
                pub trait Guest {
                    /// Initialize the scheduler. Returns error string on failure.
                    fn init() -> Result<(), _rt::String>;
                    /// Process one tick. Returns actions to fire this frame.
                    /// Called by host at each minor frame.
                    fn tick(
                        minor_frame: u32,
                        major_frame: u32,
                    ) -> _rt::Vec<ScheduledAction>;
                    /// Add a schedule slot. Returns false if table full.
                    fn add_slot(slot: ScheduleSlot) -> bool;
                    /// Enable or disable a slot. Returns false if index out of range.
                    fn set_enabled(index: u32, enabled: bool) -> bool;
                    /// Get current slot count.
                    fn slot_count() -> u32;
                }
                #[doc(hidden)]
                macro_rules! __export_pulseengine_relay_scheduler_scheduler_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "pulseengine:relay-scheduler/scheduler@0.1.0#init")] unsafe
                        extern "C" fn export_init() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_init_cabi::<$ty > () } } #[unsafe
                        (export_name =
                        "cabi_post_pulseengine:relay-scheduler/scheduler@0.1.0#init")]
                        unsafe extern "C" fn _post_return_init(arg0 : * mut u8,) { unsafe
                        { $($path_to_types)*:: __post_return_init::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "pulseengine:relay-scheduler/scheduler@0.1.0#tick")] unsafe
                        extern "C" fn export_tick(arg0 : i32, arg1 : i32,) -> * mut u8 {
                        unsafe { $($path_to_types)*:: _export_tick_cabi::<$ty > (arg0,
                        arg1) } } #[unsafe (export_name =
                        "cabi_post_pulseengine:relay-scheduler/scheduler@0.1.0#tick")]
                        unsafe extern "C" fn _post_return_tick(arg0 : * mut u8,) { unsafe
                        { $($path_to_types)*:: __post_return_tick::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "pulseengine:relay-scheduler/scheduler@0.1.0#add-slot")] unsafe
                        extern "C" fn export_add_slot(arg0 : i32, arg1 : i32, arg2 : i32,
                        arg3 : i32, arg4 : i32, arg5 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_add_slot_cabi::<$ty > (arg0, arg1,
                        arg2, arg3, arg4, arg5) } } #[unsafe (export_name =
                        "pulseengine:relay-scheduler/scheduler@0.1.0#set-enabled")]
                        unsafe extern "C" fn export_set_enabled(arg0 : i32, arg1 : i32,)
                        -> i32 { unsafe { $($path_to_types)*::
                        _export_set_enabled_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "pulseengine:relay-scheduler/scheduler@0.1.0#slot-count")] unsafe
                        extern "C" fn export_slot_count() -> i32 { unsafe {
                        $($path_to_types)*:: _export_slot_count_cabi::<$ty > () } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_pulseengine_relay_scheduler_scheduler_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 3
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    pub use alloc_crate::vec::Vec;
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_relay_scheduler_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::pulseengine::relay_scheduler::scheduler::__export_pulseengine_relay_scheduler_scheduler_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::pulseengine::relay_scheduler::scheduler);
    };
}
#[doc(inline)]
pub(crate) use __export_relay_scheduler_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:pulseengine:relay-scheduler@0.1.0:relay-scheduler:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 560] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xaa\x03\x01A\x02\x01\
A\x02\x01B\x10\x01r\x03\x0etarget-channely\x0epayload-offsety\x0bpayload-leny\x04\
\0\x10scheduled-action\x03\0\0\x01r\x06\x0bminor-framey\x0bmajor-framey\x0etarge\
t-channely\x0epayload-offsety\x0bpayload-leny\x07enabled\x7f\x04\0\x0dschedule-s\
lot\x03\0\x02\x01j\0\x01s\x01@\0\0\x04\x04\0\x04init\x01\x05\x01p\x01\x01@\x02\x0b\
minor-framey\x0bmajor-framey\0\x06\x04\0\x04tick\x01\x07\x01@\x01\x04slot\x03\0\x7f\
\x04\0\x08add-slot\x01\x08\x01@\x02\x05indexy\x07enabled\x7f\0\x7f\x04\0\x0bset-\
enabled\x01\x09\x01@\0\0y\x04\0\x0aslot-count\x01\x0a\x04\0+pulseengine:relay-sc\
heduler/scheduler@0.1.0\x05\0\x04\01pulseengine:relay-scheduler/relay-scheduler@\
0.1.0\x04\0\x0b\x15\x01\0\x0frelay-scheduler\x03\0\0\0G\x09producers\x01\x0cproc\
essed-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
