//! falcon-ekf-bench — synthetic-IMU attitude-estimator accuracy bench.
//!
//! Runs the v0.2 [`relay-ekf`] Mahony complementary filter against a
//! deterministic synthetic flight trajectory and reports tracking
//! accuracy. Used as:
//!
//!   - a runnable demo (`cargo run -p falcon-ekf-bench`),
//!   - a CI gate (the script returns non-zero if accuracy regresses),
//!   - the v0.2 acceptance test referenced in
//!     `artifacts/verification/FV-FALCON-EKF-001.yaml`.
//!
//! ## Trajectory
//!
//! 25-second sequence at 200 Hz IMU rate:
//!
//! | t (s)   | phase                  | true gyro (rad/s)     |
//! |---------|------------------------|-----------------------|
//! | 0 – 5   | at rest, 20° pitched  | (0, 0, 0)             |
//! | 5 – 10  | roll at 0.3 rad/s     | (0.3, 0, 0)           |
//! | 10 – 15 | at new attitude       | (0, 0, 0)             |
//! | 15 – 20 | yaw at 0.5 rad/s      | (0, 0, 0.5)           |
//! | 20 – 25 | at rest               | (0, 0, 0)             |
//!
//! The estimator starts at identity orientation. Ground-truth
//! attitude is generated by Euler-integrating the gyro signal over
//! the trajectory; body-frame accelerometer is the rotated gravity
//! vector. Optional white noise is added on top.
//!
//! ## Pass criterion
//!
//! - RMS attitude error over the last 2.5 s of the trajectory must
//!   be ≤ 5°.
//! - Final (steady-state) attitude error must be ≤ 5°.
//! - No NaN/∞ in the estimator output at any sample.
//!
//! Note: the final-error budget includes residual yaw drift after the
//! 25-second trajectory's yaw phase. An accelerometer-only Mahony
//! filter cannot observe heading directly — gravity gives roll/pitch
//! but not yaw — so a small steady-state yaw bias is fundamental.
//! Magnetometer fusion (v0.4 alongside `relay-att`) tightens this.
//!
//! Failures print a diff and exit with code 1.

use std::process::ExitCode;
use std::time::Instant;

use libm::{cosf, sinf, sqrtf};
use relay_ekf::{quat_mul, Ekf, ImuSample, Timestamp};

const SAMPLE_RATE_HZ: f32 = 200.0;
const TRAJECTORY_SECONDS: f32 = 25.0;
const GRAVITY: f32 = 9.81;

/// Phase boundaries and gyro signals for the test trajectory.
const PHASES: &[(f32, f32, [f32; 3])] = &[
    (0.0,  5.0,  [0.0, 0.0, 0.0]),   // rest at 20° pitch
    (5.0,  10.0, [0.3, 0.0, 0.0]),   // roll right
    (10.0, 15.0, [0.0, 0.0, 0.0]),   // rest
    (15.0, 20.0, [0.0, 0.0, 0.5]),   // yaw left
    (20.0, 25.0, [0.0, 0.0, 0.0]),   // rest
];

/// Initial true attitude: 20° pitch (about body-y).
fn initial_truth() -> [f32; 4] {
    let half = (20.0_f32).to_radians() * 0.5;
    [cosf(half), 0.0, sinf(half), 0.0]
}

/// Look up the commanded body-frame gyro at time `t`.
fn gyro_at(t: f32) -> [f32; 3] {
    for &(t0, t1, ref g) in PHASES {
        if t >= t0 && t < t1 {
            return *g;
        }
    }
    [0.0, 0.0, 0.0]
}

/// Rotate a NED-frame vector into body frame using a body-to-NED
/// quaternion `q`. (Same convention as `relay-ekf`.)
fn rotate_ned_to_body(q: [f32; 4], v: [f32; 3]) -> [f32; 3] {
    let qv = [0.0, v[0], v[1], v[2]];
    let qc = [q[0], -q[1], -q[2], -q[3]];
    let t = quat_mul(qc, quat_mul(qv, q));
    [t[1], t[2], t[3]]
}

/// Integrate ground-truth quaternion forward one tick under a
/// constant body-frame gyro vector.
fn integrate_truth(q: [f32; 4], omega_body: [f32; 3], dt: f32) -> [f32; 4] {
    let qdot = quat_mul(q, [0.0, omega_body[0], omega_body[1], omega_body[2]]);
    let q_new = [
        q[0] + 0.5 * qdot[0] * dt,
        q[1] + 0.5 * qdot[1] * dt,
        q[2] + 0.5 * qdot[2] * dt,
        q[3] + 0.5 * qdot[3] * dt,
    ];
    let n = sqrtf(
        q_new[0] * q_new[0] + q_new[1] * q_new[1]
            + q_new[2] * q_new[2] + q_new[3] * q_new[3],
    );
    if n < 1.0e-12 {
        q
    } else {
        [q_new[0] / n, q_new[1] / n, q_new[2] / n, q_new[3] / n]
    }
}

/// Angle (rad) between two unit quaternions, taking the shorter arc.
fn quat_error_rad(a: [f32; 4], b: [f32; 4]) -> f32 {
    let dot = (a[0] * b[0] + a[1] * b[1] + a[2] * b[2] + a[3] * b[3]).abs();
    let c = dot.clamp(-1.0, 1.0);
    2.0 * libm::acosf(c)
}

#[derive(Debug)]
struct BenchResult {
    samples: usize,
    rms_error_deg_full: f32,
    rms_error_deg_steady: f32, // last 2.5 s
    peak_error_deg: f32,
    final_error_deg: f32,
    convergence_time_s: f32,   // first time error drops below 5° and stays there
    elapsed_micros: u128,
    nan_seen: bool,
}

fn run_bench(noise_std: f32) -> BenchResult {
    let mut ekf = Ekf::new();
    let mut truth = initial_truth();
    let dt = 1.0 / SAMPLE_RATE_HZ;

    let total_samples = (TRAJECTORY_SECONDS * SAMPLE_RATE_HZ) as usize;
    let steady_start = (((TRAJECTORY_SECONDS - 2.5).max(0.0)) * SAMPLE_RATE_HZ) as usize;

    let mut sum_sq_full = 0.0_f32;
    let mut sum_sq_steady = 0.0_f32;
    let mut steady_count = 0usize;
    let mut peak = 0.0_f32;
    let mut final_err = 0.0_f32;
    let mut convergence_t = f32::NAN;
    let mut convergence_holding = false;
    let mut nan_seen = false;

    // Tiny pseudo-random generator (LCG) seeded deterministically.
    // We don't depend on `rand` so the bench remains no_std-friendly
    // in spirit, even though this binary uses std for I/O.
    let mut rng_state: u32 = 0xCAFEBABE;
    let mut noise = || -> f32 {
        rng_state = rng_state.wrapping_mul(1664525).wrapping_add(1013904223);
        // Map u32 → roughly N(0, 1) via two-sample averaging
        let a = ((rng_state >> 16) as f32) / (u16::MAX as f32) - 0.5;
        rng_state = rng_state.wrapping_mul(1664525).wrapping_add(1013904223);
        let b = ((rng_state >> 16) as f32) / (u16::MAX as f32) - 0.5;
        (a + b) * noise_std
    };

    let t0 = Instant::now();
    for i in 0..total_samples {
        let t = i as f32 * dt;
        let gyro_true = gyro_at(t);
        truth = integrate_truth(truth, gyro_true, dt);
        let accel_true = rotate_ned_to_body(truth, [0.0, 0.0, GRAVITY]);
        let accel_meas = [
            accel_true[0] + noise(),
            accel_true[1] + noise(),
            accel_true[2] + noise(),
        ];
        let gyro_meas = [
            gyro_true[0] + noise() * 0.1,
            gyro_true[1] + noise() * 0.1,
            gyro_true[2] + noise() * 0.1,
        ];
        let frac = ((t.fract() as f64) * ((1u64 << 32) as f64)) as u32;
        let sample = ImuSample {
            time: Timestamp { seconds: t as u64, fraction: frac },
            accel_body: accel_meas,
            gyro_body: gyro_meas,
        };
        let st = ekf.tick(sample);
        if !st.quaternion[0].is_finite() || !st.innovation.is_finite() {
            nan_seen = true;
        }
        let err_rad = quat_error_rad(truth, st.quaternion);
        let err_deg = err_rad.to_degrees();
        sum_sq_full += err_deg * err_deg;
        if i >= steady_start {
            sum_sq_steady += err_deg * err_deg;
            steady_count += 1;
        }
        if err_deg > peak {
            peak = err_deg;
        }
        final_err = err_deg;
        if err_deg < 5.0 && !convergence_holding {
            convergence_t = t;
            convergence_holding = true;
        } else if err_deg >= 5.0 && convergence_holding {
            convergence_t = f32::NAN;
            convergence_holding = false;
        }
    }
    let elapsed = t0.elapsed().as_micros();

    BenchResult {
        samples: total_samples,
        rms_error_deg_full: sqrtf(sum_sq_full / total_samples as f32),
        rms_error_deg_steady: sqrtf(sum_sq_steady / steady_count.max(1) as f32),
        peak_error_deg: peak,
        final_error_deg: final_err,
        convergence_time_s: convergence_t,
        elapsed_micros: elapsed,
        nan_seen,
    }
}

fn print_result(label: &str, r: &BenchResult) {
    println!("--- {label} ---");
    println!("  samples              {}", r.samples);
    println!("  RMS error (full)     {:.3}°", r.rms_error_deg_full);
    println!("  RMS error (steady)   {:.3}°  (last 2.5 s)", r.rms_error_deg_steady);
    println!("  peak error           {:.3}°", r.peak_error_deg);
    println!("  final error          {:.3}°", r.final_error_deg);
    if r.convergence_time_s.is_nan() {
        println!("  convergence time     never");
    } else {
        println!("  convergence time     {:.2}s  (first sustained <5°)", r.convergence_time_s);
    }
    println!("  estimator wall time  {} µs", r.elapsed_micros);
    println!("  NaN/∞ seen           {}", r.nan_seen);
}

fn print_help() {
    eprintln!(
        "falcon-ekf-bench — v0.2 attitude-estimator accuracy bench\n\n\
         USAGE:\n  \
           falcon-ekf-bench [--noise SIGMA] [--quiet]\n\n\
         Runs a deterministic 25-second synthetic IMU trajectory through\n\
         the relay-ekf Mahony filter, reports RMS attitude error in\n\
         degrees, exits 0 on PASS / 1 on FAIL.\n\n\
         OPTIONS:\n  \
           --noise SIGMA   accelerometer / gyro white-noise σ (default 0.0)\n  \
           --quiet         only print PASS/FAIL line\n  \
           --help          this text\n"
    );
}

fn main() -> ExitCode {
    let mut noise = 0.0_f32;
    let mut quiet = false;
    let mut args = std::env::args();
    args.next();
    while let Some(a) = args.next() {
        match a.as_str() {
            "--noise" => match args.next().and_then(|s| s.parse::<f32>().ok()) {
                Some(v) if v >= 0.0 => noise = v,
                _ => {
                    eprintln!("error: --noise expects a non-negative float");
                    return ExitCode::from(2);
                }
            },
            "--quiet" => quiet = true,
            "--help" | "-h" => {
                print_help();
                return ExitCode::SUCCESS;
            }
            other => {
                eprintln!("error: unknown argument {other}");
                print_help();
                return ExitCode::from(2);
            }
        }
    }

    let clean = run_bench(0.0);
    if !quiet {
        print_result("noise=0 (deterministic)", &clean);
    }

    let noisy = if noise > 0.0 {
        let r = run_bench(noise);
        if !quiet {
            print_result(&format!("noise σ={noise}"), &r);
        }
        Some(r)
    } else {
        None
    };

    // Pass criteria — these double as the v0.2 acceptance test.
    // Final-error tolerance is 5° (not tighter): an accel-only Mahony
    // filter cannot observe heading from gravity, so residual yaw
    // drift after the trajectory's yaw phase is fundamental until
    // v0.4 wires magnetometer fusion.
    let pass_clean = clean.rms_error_deg_steady <= 5.0
        && clean.final_error_deg <= 5.0
        && !clean.nan_seen;
    let pass_noisy = noisy.as_ref().map_or(true, |r| {
        r.rms_error_deg_steady <= 8.0  // looser tolerance with noise
            && r.final_error_deg <= 8.0
            && !r.nan_seen
    });

    if pass_clean && pass_noisy {
        println!("falcon-ekf-bench: PASS");
        ExitCode::SUCCESS
    } else {
        println!(
            "falcon-ekf-bench: FAIL  (clean: rms_steady={:.2}° final={:.2}°)",
            clean.rms_error_deg_steady, clean.final_error_deg
        );
        ExitCode::from(1)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Round-trip the synthetic trajectory through the estimator
    /// with zero noise; assert it tracks within the v0.2 pass band.
    #[test]
    fn deterministic_bench_passes() {
        let r = run_bench(0.0);
        assert!(!r.nan_seen);
        assert!(
            r.rms_error_deg_steady <= 5.0,
            "RMS steady error {}° exceeds 5° budget", r.rms_error_deg_steady
        );
        assert!(
            r.final_error_deg <= 5.0,
            "final error {}° exceeds 5° budget", r.final_error_deg
        );
    }

    /// Noise should not destabilise the estimator within reasonable
    /// bounds for a commodity-grade IMU (σ ≤ 0.5 m/s² on accel).
    #[test]
    fn noisy_bench_passes_loose() {
        let r = run_bench(0.2);
        assert!(!r.nan_seen);
        assert!(
            r.rms_error_deg_steady <= 8.0,
            "noisy RMS steady error {}° exceeds 8° budget",
            r.rms_error_deg_steady,
        );
        assert!(
            r.final_error_deg <= 8.0,
            "noisy final error {}° exceeds 8° budget",
            r.final_error_deg,
        );
    }

    #[test]
    fn phases_are_consistent_with_trajectory_duration() {
        let last = PHASES.last().unwrap();
        assert!((last.1 - TRAJECTORY_SECONDS).abs() < 1.0e-6);
        // No gaps or overlaps.
        for w in PHASES.windows(2) {
            assert!((w[0].1 - w[1].0).abs() < 1.0e-6);
        }
    }

    #[test]
    fn quat_error_is_zero_for_identical_quaternions() {
        let q = [1.0, 0.0, 0.0, 0.0];
        assert!(quat_error_rad(q, q) < 1.0e-6);
    }

    #[test]
    fn rotate_ned_to_body_identity_passes_through() {
        let v = [1.0, 2.0, 3.0];
        let r = rotate_ned_to_body([1.0, 0.0, 0.0, 0.0], v);
        for k in 0..3 {
            assert!((r[k] - v[k]).abs() < 1.0e-6);
        }
    }
}
