//! falcon-attitude — the attitude controller as a Component Model
//! component. Wraps `relay-att::AttController`.
//!
//! The attitude controller is P-only (no integrator) but the
//! component still carries the `AttController` instance for gains
//! and diagnostics. Timestamps synthesised as a 250 Hz counter.

// Bindings generated by cargo-component as src/bindings.rs.
#[allow(warnings)]
mod bindings;

use core::cell::RefCell;

use bindings::exports::falcon::cascade::attitude::Guest;
use bindings::falcon::cascade::types::{AttitudeSetpoint, RateSetpoint, VehicleState};

use relay_att::{AttController, Timestamp};

thread_local! {
    static ATT: RefCell<AttController> = RefCell::new(AttController::new());
    static TICK: RefCell<u64> = const { RefCell::new(0) };
}

fn next_timestamp() -> Timestamp {
    TICK.with(|c| {
        let n = *c.borrow();
        *c.borrow_mut() = n + 1;
        // 250 Hz → 4 ms per tick.
        let ms = n * 4;
        Timestamp {
            seconds: ms / 1000,
            fraction: ((ms % 1000) * (1u64 << 32) / 1000) as u32,
        }
    })
}

struct Component;

impl Guest for Component {
    fn tick(state: VehicleState, sp: AttitudeSetpoint) -> RateSetpoint {
        let rate = ATT.with(|a| {
            a.borrow_mut().tick(
                next_timestamp(),
                [state.qw, state.qx, state.qy, state.qz],
                [sp.qw, sp.qx, sp.qy, sp.qz],
            )
        });
        RateSetpoint {
            rx: rate[0],
            ry: rate[1],
            rz: rate[2],
            // Thrust passes straight through the attitude loop.
            thrust: sp.thrust,
        }
    }
}

bindings::export!(Component with_types_in bindings);
