//! falcon-attitude — the attitude controller as a Component Model
//! component. Wraps `relay-att::AttController`.
//!
//! The attitude controller is P-only (no integrator) but the
//! component still carries the `AttController` instance for gains
//! and diagnostics. Timestamps synthesised as a 250 Hz counter.

#![cfg_attr(not(feature = "std"), no_std)]

// Bounded work-memory arena + the canonical-ABI `cabi_realloc` export + a panic
// handler, from the shared crate so the `unsafe` lives in one audited place.
// no_std keeps the component free of WASI and of `memory.grow`, which is what
// blocks `meld fuse --memory shared --address-rebase` (gale#89, meld#299).
#[cfg(not(feature = "std"))]
falcon_cm_rt::export_cm_rt!();

// Bindings generated by cargo-component as src/bindings.rs.
#[allow(warnings)]
#[cfg(feature = "bazel-bindings")]
use falcon_attitude_bindings as bindings;
#[cfg(not(feature = "bazel-bindings"))]
mod bindings;

use core::cell::RefCell;

/// A component instance is single-threaded and never re-entered concurrently by
/// the runtime, so a `Sync` cell is sound. Replaces `thread_local!`, whose
/// `std` dependency was what pulled the WASI imports in.
struct SingleThreaded<T>(RefCell<T>);
// SAFETY: the component model guarantees single-threaded, non-reentrant access.
unsafe impl<T> Sync for SingleThreaded<T> {}

use bindings::exports::pulseengine::falcon_cascade::attitude::Guest;
use bindings::pulseengine::falcon_cascade::types::{AttitudeSetpoint, RateSetpoint, VehicleState};

use relay_att::{AttController, Timestamp};

static ATT: SingleThreaded<AttController> = SingleThreaded(RefCell::new(AttController::new()));
static TICK: SingleThreaded<u64> = SingleThreaded(RefCell::new(0));

fn next_timestamp() -> Timestamp {
    { let c = &TICK.0;
        let n = *c.borrow();
        *c.borrow_mut() = n + 1;
        // 250 Hz → 4 ms per tick.
        let ms = n * 4;
        Timestamp {
            seconds: ms / 1000,
            fraction: ((ms % 1000) * (1u64 << 32) / 1000) as u32,
        }
    }
}

struct Component;

impl Guest for Component {
    fn tick(state: VehicleState, sp: AttitudeSetpoint) -> RateSetpoint {
        let rate = { let a = &ATT.0;
            a.borrow_mut().tick(
                next_timestamp(),
                [state.qw, state.qx, state.qy, state.qz],
                [sp.qw, sp.qx, sp.qy, sp.qz],
            )
        };
        RateSetpoint {
            rx: rate[0],
            ry: rate[1],
            rz: rate[2],
            // Thrust passes straight through the attitude loop.
            thrust: sp.thrust,
        }
    }
}

bindings::export!(Component with_types_in bindings);
