// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod pulseengine {
        pub mod relay_limit_checker {
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod limit_checker {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct SensorReading {
                    pub sensor_id: u32,
                    pub value: i64,
                }
                impl ::core::fmt::Debug for SensorReading {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("SensorReading")
                            .field("sensor-id", &self.sensor_id)
                            .field("value", &self.value)
                            .finish()
                    }
                }
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct Violation {
                    pub watchpoint_id: u32,
                    pub measured: i64,
                    pub threshold: i64,
                }
                impl ::core::fmt::Debug for Violation {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Violation")
                            .field("watchpoint-id", &self.watchpoint_id)
                            .field("measured", &self.measured)
                            .field("threshold", &self.threshold)
                            .finish()
                    }
                }
                #[repr(u8)]
                #[derive(Clone, Copy, Eq, Ord, PartialEq, PartialOrd)]
                pub enum ComparisonOp {
                    LessThan,
                    GreaterThan,
                    LessOrEqual,
                    GreaterOrEqual,
                    Equal,
                    NotEqual,
                }
                impl ::core::fmt::Debug for ComparisonOp {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        match self {
                            ComparisonOp::LessThan => {
                                f.debug_tuple("ComparisonOp::LessThan").finish()
                            }
                            ComparisonOp::GreaterThan => {
                                f.debug_tuple("ComparisonOp::GreaterThan").finish()
                            }
                            ComparisonOp::LessOrEqual => {
                                f.debug_tuple("ComparisonOp::LessOrEqual").finish()
                            }
                            ComparisonOp::GreaterOrEqual => {
                                f.debug_tuple("ComparisonOp::GreaterOrEqual").finish()
                            }
                            ComparisonOp::Equal => {
                                f.debug_tuple("ComparisonOp::Equal").finish()
                            }
                            ComparisonOp::NotEqual => {
                                f.debug_tuple("ComparisonOp::NotEqual").finish()
                            }
                        }
                    }
                }
                impl ComparisonOp {
                    #[doc(hidden)]
                    pub unsafe fn _lift(val: u8) -> ComparisonOp {
                        if !cfg!(debug_assertions) {
                            return ::core::mem::transmute(val);
                        }
                        match val {
                            0 => ComparisonOp::LessThan,
                            1 => ComparisonOp::GreaterThan,
                            2 => ComparisonOp::LessOrEqual,
                            3 => ComparisonOp::GreaterOrEqual,
                            4 => ComparisonOp::Equal,
                            5 => ComparisonOp::NotEqual,
                            _ => panic!("invalid enum discriminant"),
                        }
                    }
                }
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct Watchpoint {
                    pub sensor_id: u32,
                    pub op: ComparisonOp,
                    pub threshold: i64,
                    pub enabled: bool,
                    pub persistence: u32,
                }
                impl ::core::fmt::Debug for Watchpoint {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("Watchpoint")
                            .field("sensor-id", &self.sensor_id)
                            .field("op", &self.op)
                            .field("threshold", &self.threshold)
                            .field("enabled", &self.enabled)
                            .field("persistence", &self.persistence)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_init_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::init();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(_) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_init<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_add_watchpoint_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i64,
                    arg3: i32,
                    arg4: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::add_watchpoint(Watchpoint {
                        sensor_id: arg0 as u32,
                        op: ComparisonOp::_lift(arg1 as u8),
                        threshold: arg2,
                        enabled: _rt::bool_lift(arg3 as u8),
                        persistence: arg4 as u32,
                    });
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_evaluate_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i64,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::evaluate(SensorReading {
                        sensor_id: arg0 as u32,
                        value: arg1,
                    });
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    let vec2 = (result0).into_boxed_slice();
                    let ptr2 = vec2.as_ptr().cast::<u8>();
                    let len2 = vec2.len();
                    ::core::mem::forget(vec2);
                    *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
                    *ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_evaluate<T: Guest>(arg0: *mut u8) {
                    let l0 = *arg0.add(0).cast::<*mut u8>();
                    let l1 = *arg0
                        .add(::core::mem::size_of::<*const u8>())
                        .cast::<usize>();
                    let base2 = l0;
                    let len2 = l1;
                    _rt::cabi_dealloc(base2, len2 * 24, 8);
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_count_cabi<T: Guest>() -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::count();
                    _rt::as_i32(result0)
                }
                pub trait Guest {
                    fn init() -> Result<(), _rt::String>;
                    fn add_watchpoint(wp: Watchpoint) -> bool;
                    fn evaluate(reading: SensorReading) -> _rt::Vec<Violation>;
                    fn count() -> u32;
                }
                #[doc(hidden)]
                macro_rules! __export_pulseengine_relay_limit_checker_limit_checker_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "pulseengine:relay-limit-checker/limit-checker@0.1.0#init")]
                        unsafe extern "C" fn export_init() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_init_cabi::<$ty > () } } #[unsafe
                        (export_name =
                        "cabi_post_pulseengine:relay-limit-checker/limit-checker@0.1.0#init")]
                        unsafe extern "C" fn _post_return_init(arg0 : * mut u8,) { unsafe
                        { $($path_to_types)*:: __post_return_init::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "pulseengine:relay-limit-checker/limit-checker@0.1.0#add-watchpoint")]
                        unsafe extern "C" fn export_add_watchpoint(arg0 : i32, arg1 :
                        i32, arg2 : i64, arg3 : i32, arg4 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_add_watchpoint_cabi::<$ty > (arg0,
                        arg1, arg2, arg3, arg4) } } #[unsafe (export_name =
                        "pulseengine:relay-limit-checker/limit-checker@0.1.0#evaluate")]
                        unsafe extern "C" fn export_evaluate(arg0 : i32, arg1 : i64,) ->
                        * mut u8 { unsafe { $($path_to_types)*::
                        _export_evaluate_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_pulseengine:relay-limit-checker/limit-checker@0.1.0#evaluate")]
                        unsafe extern "C" fn _post_return_evaluate(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_evaluate::<$ty >
                        (arg0) } } #[unsafe (export_name =
                        "pulseengine:relay-limit-checker/limit-checker@0.1.0#count")]
                        unsafe extern "C" fn export_count() -> i32 { unsafe {
                        $($path_to_types)*:: _export_count_cabi::<$ty > () } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_pulseengine_relay_limit_checker_limit_checker_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 3
                        * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    pub unsafe fn bool_lift(val: u8) -> bool {
        if cfg!(debug_assertions) {
            match val {
                0 => false,
                1 => true,
                _ => panic!("invalid bool discriminant"),
            }
        } else {
            val != 0
        }
    }
    pub use alloc_crate::vec::Vec;
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    pub use alloc_crate::alloc;
    extern crate alloc as alloc_crate;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_relay_limit_checker_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::pulseengine::relay_limit_checker::limit_checker::__export_pulseengine_relay_limit_checker_limit_checker_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::pulseengine::relay_limit_checker::limit_checker);
    };
}
#[doc(inline)]
pub(crate) use __export_relay_limit_checker_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:pulseengine:relay-limit-checker@0.1.0:relay-limit-checker:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 611] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xd9\x03\x01A\x02\x01\
A\x02\x01B\x12\x01r\x02\x09sensor-idy\x05valuex\x04\0\x0esensor-reading\x03\0\0\x01\
r\x03\x0dwatchpoint-idy\x08measuredx\x09thresholdx\x04\0\x09violation\x03\0\x02\x01\
m\x06\x09less-than\x0cgreater-than\x0dless-or-equal\x10greater-or-equal\x05equal\
\x09not-equal\x04\0\x0dcomparison-op\x03\0\x04\x01r\x05\x09sensor-idy\x02op\x05\x09\
thresholdx\x07enabled\x7f\x0bpersistencey\x04\0\x0awatchpoint\x03\0\x06\x01j\0\x01\
s\x01@\0\0\x08\x04\0\x04init\x01\x09\x01@\x01\x02wp\x07\0\x7f\x04\0\x0eadd-watch\
point\x01\x0a\x01p\x03\x01@\x01\x07reading\x01\0\x0b\x04\0\x08evaluate\x01\x0c\x01\
@\0\0y\x04\0\x05count\x01\x0d\x04\03pulseengine:relay-limit-checker/limit-checke\
r@0.1.0\x05\0\x04\09pulseengine:relay-limit-checker/relay-limit-checker@0.1.0\x04\
\0\x0b\x19\x01\0\x13relay-limit-checker\x03\0\0\0G\x09producers\x01\x0cprocessed\
-by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
