//! falcon-position — the position controller as a Component Model
//! component. Wraps `relay-pos::PosController`.
//!
//! Stateful: the cascaded P-PI integrator persists across `tick`
//! calls. Timestamps synthesised as a 50 Hz monotonic counter (the
//! position loop runs slower than the inner loops).

// Bindings generated by cargo-component as src/bindings.rs.
#[allow(warnings)]
#[cfg(feature = "bazel-bindings")]
use falcon_position_bindings as bindings;
#[cfg(not(feature = "bazel-bindings"))]
mod bindings;

use core::cell::RefCell;

use bindings::exports::pulseengine::falcon_cascade::position::Guest;
use bindings::pulseengine::falcon_cascade::types::{AttitudeSetpoint, VehicleState, Waypoint};

use relay_pos::{PosController, PositionSetpoint, Timestamp};

thread_local! {
    static POS: RefCell<PosController> = RefCell::new(PosController::new());
    static TICK: RefCell<u64> = const { RefCell::new(0) };
}

fn next_timestamp() -> Timestamp {
    TICK.with(|c| {
        let n = *c.borrow();
        *c.borrow_mut() = n + 1;
        // 50 Hz → 20 ms per tick.
        let ms = n * 20;
        Timestamp {
            seconds: ms / 1000,
            fraction: ((ms % 1000) * (1u64 << 32) / 1000) as u32,
        }
    })
}

struct Component;

impl Guest for Component {
    fn tick(state: VehicleState, target: Waypoint) -> AttitudeSetpoint {
        let setpoint = PositionSetpoint {
            position_ned: [target.north, target.east, target.down],
            velocity_ned: [0.0, 0.0, 0.0],
            yaw_setpoint: target.yaw,
        };
        let att = POS.with(|p| {
            p.borrow_mut().tick(
                next_timestamp(),
                [state.pos_n, state.pos_e, state.pos_d],
                [state.vel_n, state.vel_e, state.vel_d],
                [state.qw, state.qx, state.qy, state.qz],
                setpoint,
            )
        });
        AttitudeSetpoint {
            qw: att.quaternion[0],
            qx: att.quaternion[1],
            qy: att.quaternion[2],
            qz: att.quaternion[3],
            thrust: att.thrust,
        }
    }
}

bindings::export!(Component with_types_in bindings);
