// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
// Options used:
//   * runtime_path: "wit_bindgen_rt"
#[rustfmt::skip]
#[allow(dead_code, clippy::all)]
pub mod exports {
    pub mod pulseengine {
        pub mod relay_housekeeping {
            /// Housekeeping — stream combiner: copies fields from sources into HK packets.
            ///
            /// The host configures copy entries that describe which bytes to copy
            /// from which source into the output packet. On collect(), all entries
            /// are applied and an HK packet is produced.
            ///
            /// P3 async: all functions are async fn — the host can call without blocking.
            #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
            pub mod housekeeping {
                #[used]
                #[doc(hidden)]
                static __FORCE_SECTION_REF: fn() = super::super::super::super::__link_custom_section_describing_imports;
                use super::super::super::super::_rt;
                /// A copy-table entry describing one field copy.
                #[repr(C)]
                #[derive(Clone, Copy)]
                pub struct CopyEntry {
                    pub source_id: u32,
                    pub source_offset: u32,
                    pub length: u32,
                    pub output_offset: u32,
                }
                impl ::core::fmt::Debug for CopyEntry {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("CopyEntry")
                            .field("source-id", &self.source_id)
                            .field("source-offset", &self.source_offset)
                            .field("length", &self.length)
                            .field("output-offset", &self.output_offset)
                            .finish()
                    }
                }
                /// Source data block (fixed 64 bytes).
                #[derive(Clone)]
                pub struct SourceData {
                    pub source_id: u32,
                    pub data: _rt::Vec<u8>,
                }
                impl ::core::fmt::Debug for SourceData {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("SourceData")
                            .field("source-id", &self.source_id)
                            .field("data", &self.data)
                            .finish()
                    }
                }
                /// An assembled housekeeping packet.
                #[derive(Clone)]
                pub struct HkPacket {
                    pub data: _rt::Vec<u8>,
                    pub length: u32,
                    pub sequence: u32,
                }
                impl ::core::fmt::Debug for HkPacket {
                    fn fmt(
                        &self,
                        f: &mut ::core::fmt::Formatter<'_>,
                    ) -> ::core::fmt::Result {
                        f.debug_struct("HkPacket")
                            .field("data", &self.data)
                            .field("length", &self.length)
                            .field("sequence", &self.sequence)
                            .finish()
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_init_cabi<T: Guest>() -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::init();
                    let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result0 {
                        Ok(_) => {
                            *ptr1.add(0).cast::<u8>() = (0i32) as u8;
                        }
                        Err(e) => {
                            *ptr1.add(0).cast::<u8>() = (1i32) as u8;
                            let vec2 = (e.into_bytes()).into_boxed_slice();
                            let ptr2 = vec2.as_ptr().cast::<u8>();
                            let len2 = vec2.len();
                            ::core::mem::forget(vec2);
                            *ptr1
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len2;
                            *ptr1
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr2.cast_mut();
                        }
                    };
                    ptr1
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_init<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            _rt::cabi_dealloc(l1, l2, 1);
                        }
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_add_copy_entry_cabi<T: Guest>(
                    arg0: i32,
                    arg1: i32,
                    arg2: i32,
                    arg3: i32,
                ) -> i32 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let result0 = T::add_copy_entry(CopyEntry {
                        source_id: arg0 as u32,
                        source_offset: arg1 as u32,
                        length: arg2 as u32,
                        output_offset: arg3 as u32,
                    });
                    match result0 {
                        true => 1,
                        false => 0,
                    }
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn _export_collect_cabi<T: Guest>(
                    arg0: *mut u8,
                    arg1: usize,
                ) -> *mut u8 {
                    #[cfg(target_arch = "wasm32")] _rt::run_ctors_once();
                    let base4 = arg0;
                    let len4 = arg1;
                    let mut result4 = _rt::Vec::with_capacity(len4);
                    for i in 0..len4 {
                        let base = base4
                            .add(i * (3 * ::core::mem::size_of::<*const u8>()));
                        let e4 = {
                            let l0 = *base.add(0).cast::<i32>();
                            let l1 = *base
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *base
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let len3 = l2;
                            SourceData {
                                source_id: l0 as u32,
                                data: _rt::Vec::from_raw_parts(l1.cast(), len3, len3),
                            }
                        };
                        result4.push(e4);
                    }
                    _rt::cabi_dealloc(
                        base4,
                        len4 * (3 * ::core::mem::size_of::<*const u8>()),
                        ::core::mem::size_of::<*const u8>(),
                    );
                    let result5 = T::collect(result4);
                    let ptr6 = (&raw mut _RET_AREA.0).cast::<u8>();
                    match result5 {
                        Some(e) => {
                            *ptr6.add(0).cast::<u8>() = (1i32) as u8;
                            let HkPacket {
                                data: data7,
                                length: length7,
                                sequence: sequence7,
                            } = e;
                            let vec8 = (data7).into_boxed_slice();
                            let ptr8 = vec8.as_ptr().cast::<u8>();
                            let len8 = vec8.len();
                            ::core::mem::forget(vec8);
                            *ptr6
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>() = len8;
                            *ptr6
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>() = ptr8.cast_mut();
                            *ptr6
                                .add(3 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(length7);
                            *ptr6
                                .add(4 + 3 * ::core::mem::size_of::<*const u8>())
                                .cast::<i32>() = _rt::as_i32(sequence7);
                        }
                        None => {
                            *ptr6.add(0).cast::<u8>() = (0i32) as u8;
                        }
                    };
                    ptr6
                }
                #[doc(hidden)]
                #[allow(non_snake_case)]
                pub unsafe fn __post_return_collect<T: Guest>(arg0: *mut u8) {
                    let l0 = i32::from(*arg0.add(0).cast::<u8>());
                    match l0 {
                        0 => {}
                        _ => {
                            let l1 = *arg0
                                .add(::core::mem::size_of::<*const u8>())
                                .cast::<*mut u8>();
                            let l2 = *arg0
                                .add(2 * ::core::mem::size_of::<*const u8>())
                                .cast::<usize>();
                            let base3 = l1;
                            let len3 = l2;
                            _rt::cabi_dealloc(base3, len3 * 1, 1);
                        }
                    }
                }
                pub trait Guest {
                    /// Initialize the housekeeping engine. Returns error string on failure.
                    fn init() -> Result<(), _rt::String>;
                    /// Add a copy entry. Returns false if table full.
                    fn add_copy_entry(entry: CopyEntry) -> bool;
                    /// Collect data from sources into an HK packet. Returns none on failure.
                    fn collect(sources: _rt::Vec<SourceData>) -> Option<HkPacket>;
                }
                #[doc(hidden)]
                macro_rules! __export_pulseengine_relay_housekeeping_housekeeping_0_1_0_cabi {
                    ($ty:ident with_types_in $($path_to_types:tt)*) => {
                        const _ : () = { #[unsafe (export_name =
                        "pulseengine:relay-housekeeping/housekeeping@0.1.0#init")] unsafe
                        extern "C" fn export_init() -> * mut u8 { unsafe {
                        $($path_to_types)*:: _export_init_cabi::<$ty > () } } #[unsafe
                        (export_name =
                        "cabi_post_pulseengine:relay-housekeeping/housekeeping@0.1.0#init")]
                        unsafe extern "C" fn _post_return_init(arg0 : * mut u8,) { unsafe
                        { $($path_to_types)*:: __post_return_init::<$ty > (arg0) } }
                        #[unsafe (export_name =
                        "pulseengine:relay-housekeeping/housekeeping@0.1.0#add-copy-entry")]
                        unsafe extern "C" fn export_add_copy_entry(arg0 : i32, arg1 :
                        i32, arg2 : i32, arg3 : i32,) -> i32 { unsafe {
                        $($path_to_types)*:: _export_add_copy_entry_cabi::<$ty > (arg0,
                        arg1, arg2, arg3) } } #[unsafe (export_name =
                        "pulseengine:relay-housekeeping/housekeeping@0.1.0#collect")]
                        unsafe extern "C" fn export_collect(arg0 : * mut u8, arg1 :
                        usize,) -> * mut u8 { unsafe { $($path_to_types)*::
                        _export_collect_cabi::<$ty > (arg0, arg1) } } #[unsafe
                        (export_name =
                        "cabi_post_pulseengine:relay-housekeeping/housekeeping@0.1.0#collect")]
                        unsafe extern "C" fn _post_return_collect(arg0 : * mut u8,) {
                        unsafe { $($path_to_types)*:: __post_return_collect::<$ty >
                        (arg0) } } };
                    };
                }
                #[doc(hidden)]
                pub(crate) use __export_pulseengine_relay_housekeeping_housekeeping_0_1_0_cabi;
                #[cfg_attr(target_pointer_width = "64", repr(align(8)))]
                #[cfg_attr(target_pointer_width = "32", repr(align(4)))]
                struct _RetArea(
                    [::core::mem::MaybeUninit<
                        u8,
                    >; 8 + 3 * ::core::mem::size_of::<*const u8>()],
                );
                static mut _RET_AREA: _RetArea = _RetArea(
                    [::core::mem::MaybeUninit::uninit(); 8
                        + 3 * ::core::mem::size_of::<*const u8>()],
                );
            }
        }
    }
}
#[rustfmt::skip]
mod _rt {
    #![allow(dead_code, clippy::all)]
    pub use alloc_crate::vec::Vec;
    #[cfg(target_arch = "wasm32")]
    pub fn run_ctors_once() {
        wit_bindgen_rt::run_ctors_once();
    }
    pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
        if size == 0 {
            return;
        }
        let layout = alloc::Layout::from_size_align_unchecked(size, align);
        alloc::dealloc(ptr, layout);
    }
    pub use alloc_crate::string::String;
    pub fn as_i32<T: AsI32>(t: T) -> i32 {
        t.as_i32()
    }
    pub trait AsI32 {
        fn as_i32(self) -> i32;
    }
    impl<'a, T: Copy + AsI32> AsI32 for &'a T {
        fn as_i32(self) -> i32 {
            (*self).as_i32()
        }
    }
    impl AsI32 for i32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u32 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u16 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for i8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for u8 {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for char {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    impl AsI32 for usize {
        #[inline]
        fn as_i32(self) -> i32 {
            self as i32
        }
    }
    extern crate alloc as alloc_crate;
    pub use alloc_crate::alloc;
}
/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]
macro_rules! __export_relay_housekeeping_impl {
    ($ty:ident) => {
        self::export!($ty with_types_in self);
    };
    ($ty:ident with_types_in $($path_to_types_root:tt)*) => {
        $($path_to_types_root)*::
        exports::pulseengine::relay_housekeeping::housekeeping::__export_pulseengine_relay_housekeeping_housekeeping_0_1_0_cabi!($ty
        with_types_in $($path_to_types_root)*::
        exports::pulseengine::relay_housekeeping::housekeeping);
    };
}
#[doc(inline)]
pub(crate) use __export_relay_housekeeping_impl as export;
#[cfg(target_arch = "wasm32")]
#[unsafe(
    link_section = "component-type:wit-bindgen:0.41.0:pulseengine:relay-housekeeping@0.1.0:relay-housekeeping:encoded world"
)]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 492] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xe3\x02\x01A\x02\x01\
A\x02\x01B\x10\x01r\x04\x09source-idy\x0dsource-offsety\x06lengthy\x0doutput-off\
sety\x04\0\x0acopy-entry\x03\0\0\x01p}\x01r\x02\x09source-idy\x04data\x02\x04\0\x0b\
source-data\x03\0\x03\x01r\x03\x04data\x02\x06lengthy\x08sequencey\x04\0\x09hk-p\
acket\x03\0\x05\x01j\0\x01s\x01@\0\0\x07\x04\0\x04init\x01\x08\x01@\x01\x05entry\
\x01\0\x7f\x04\0\x0eadd-copy-entry\x01\x09\x01p\x04\x01k\x06\x01@\x01\x07sources\
\x0a\0\x0b\x04\0\x07collect\x01\x0c\x04\01pulseengine:relay-housekeeping/houseke\
eping@0.1.0\x05\0\x04\07pulseengine:relay-housekeeping/relay-housekeeping@0.1.0\x04\
\0\x0b\x18\x01\0\x12relay-housekeeping\x03\0\0\0G\x09producers\x01\x0cprocessed-\
by\x02\x0dwit-component\x070.227.1\x10wit-bindgen-rust\x060.41.0";
#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
    wit_bindgen_rt::maybe_link_cabi_realloc();
}
