//! falcon-rate — the body-rate PID as a Component Model component.
//! Wraps `relay-rate::RatePid`.
//!
//! Stateful: the PID integrator + derivative state persist across `tick`
//! calls. Timestamps synthesised as a 1 kHz counter. The measured body rate
//! comes from `vehicle-state.{wx,wy,wz}` (the gyro reading the EKF component
//! passes through).
//!
//! `no_std` unless the `std` feature is on, so the component imports NO WASI — a
//! pure `pulseengine:falcon-cascade/types` -> `rate` transformer, which is what lowers to
//! bare metal (synth -> gale on M4/M7/F100) and what a WASI-less wasmtime host
//! can drive directly. (The single-threaded statics replace `thread_local!`,
//! whose `std` dependency was the sole reason WASI was linked.) The Bazel
//! bindings path keeps its existing environment.
//!
//! FEATURE SPLIT (v1.130): `bazel-bindings` selects the BINDINGS SOURCE only;
//! `std` selects std-vs-no_std. These were briefly conflated on one flag, which
//! made the Bazel build (which sets bazel-bindings) silently produce a
//! std/WASI-carrying artifact while the cargo-component build produced the
//! WASI-free one — two build systems, same source, materially different output.
//! rules_rust does not apply Cargo's default-features, so a Bazel build enables
//! ONLY the features it lists: `bazel-bindings` without `std` => no_std.

#![cfg_attr(not(feature = "std"), no_std)]

// Bounded work-memory arena + the canonical-ABI `cabi_realloc` export + a panic
// handler, from the shared crate so the `unsafe` lives in one audited place
// rather than once per component. See crates/falcon-cm-rt.
#[cfg(not(feature = "std"))]
falcon_cm_rt::export_cm_rt!();


// Bindings generated by cargo-component as src/bindings.rs.
#[allow(warnings)]
#[cfg(feature = "bazel-bindings")]
use falcon_rate_bindings as bindings;
#[cfg(not(feature = "bazel-bindings"))]
mod bindings;

use core::cell::RefCell;

use bindings::exports::pulseengine::falcon_cascade::rate::Guest;
use bindings::pulseengine::falcon_cascade::types::{RateSetpoint, TorqueSetpoint, VehicleState};

use relay_rate::{RatePid, Timestamp};

/// A wasm component instance is single-threaded and never re-entered
/// concurrently by the runtime, so wrapping the per-instance state in a
/// `Sync` cell is sound. This replaces `thread_local!` (which is `std`, and
/// pulled in the WASI imports).
struct SingleThreaded<T>(RefCell<T>);
// SAFETY: the component model guarantees single-threaded, non-reentrant access.
unsafe impl<T> Sync for SingleThreaded<T> {}

static PID: SingleThreaded<RatePid> = SingleThreaded(RefCell::new(RatePid::new()));
static TICK_MS: SingleThreaded<u64> = SingleThreaded(RefCell::new(0));

fn next_timestamp() -> Timestamp {
    let ms = *TICK_MS.0.borrow();
    *TICK_MS.0.borrow_mut() = ms + 1;
    Timestamp {
        seconds: ms / 1000,
        fraction: ((ms % 1000) * (1u64 << 32) / 1000) as u32,
    }
}

struct Component;

impl Guest for Component {
    fn tick(state: VehicleState, sp: RateSetpoint) -> TorqueSetpoint {
        // Reclaim the previous call's spilled-parameter area. The canonical ABI
        // never frees what it allocates through cabi_realloc, so without this a
        // long-running component would walk the bump cursor to exhaustion.
        // Sound here because the arena only ever holds the CURRENT call's
        // argument/result area — nothing allocated by a previous tick outlives it.
        #[cfg(not(feature = "std"))]
        falcon_cm_rt::BumpArena::reset();

        let torque = PID.0.borrow_mut().tick(
            next_timestamp(),
            [state.wx, state.wy, state.wz],
            [sp.rx, sp.ry, sp.rz],
        );
        TorqueSetpoint {
            tx: torque[0],
            ty: torque[1],
            tz: torque[2],
            // Thrust passes straight through the rate loop.
            thrust: sp.thrust,
        }
    }
}

bindings::export!(Component with_types_in bindings);

