//! falcon-rate — the body-rate PID as a Component Model component.
//! Wraps `relay-rate::RatePid`.
//!
//! Stateful: the PID integrator + derivative state persist across `tick`
//! calls. Timestamps synthesised as a 1 kHz counter. The measured body rate
//! comes from `vehicle-state.{wx,wy,wz}` (the gyro reading the EKF component
//! passes through).
//!
//! `no_std` on the cargo-component path so the component imports NO WASI — a
//! pure `falcon:cascade/types` -> `rate` transformer, which is what lowers to
//! bare metal (synth -> gale on M4/M7/F100) and what a WASI-less wasmtime host
//! can drive directly. (The single-threaded statics replace `thread_local!`,
//! whose `std` dependency was the sole reason WASI was linked.) The Bazel
//! bindings path keeps its existing environment.

#![cfg_attr(not(feature = "bazel-bindings"), no_std)]

// no_std (cargo-component path) global allocator — the component ABI's
// cabi_realloc needs one. Single-threaded is sound: a component instance is
// never re-entered concurrently by the runtime.
#[cfg(not(feature = "bazel-bindings"))]
#[global_allocator]
static ALLOC: lol_alloc::AssumeSingleThreaded<lol_alloc::FreeListAllocator> =
    unsafe { lol_alloc::AssumeSingleThreaded::new(lol_alloc::FreeListAllocator::new()) };

// Bindings generated by cargo-component as src/bindings.rs.
#[allow(warnings)]
#[cfg(feature = "bazel-bindings")]
use falcon_rate_bindings as bindings;
#[cfg(not(feature = "bazel-bindings"))]
mod bindings;

use core::cell::RefCell;

use bindings::exports::falcon::cascade::rate::Guest;
use bindings::falcon::cascade::types::{RateSetpoint, TorqueSetpoint, VehicleState};

use relay_rate::{RatePid, Timestamp};

/// A wasm component instance is single-threaded and never re-entered
/// concurrently by the runtime, so wrapping the per-instance state in a
/// `Sync` cell is sound. This replaces `thread_local!` (which is `std`, and
/// pulled in the WASI imports).
struct SingleThreaded<T>(RefCell<T>);
// SAFETY: the component model guarantees single-threaded, non-reentrant access.
unsafe impl<T> Sync for SingleThreaded<T> {}

static PID: SingleThreaded<RatePid> = SingleThreaded(RefCell::new(RatePid::new()));
static TICK_MS: SingleThreaded<u64> = SingleThreaded(RefCell::new(0));

fn next_timestamp() -> Timestamp {
    let ms = *TICK_MS.0.borrow();
    *TICK_MS.0.borrow_mut() = ms + 1;
    Timestamp {
        seconds: ms / 1000,
        fraction: ((ms % 1000) * (1u64 << 32) / 1000) as u32,
    }
}

struct Component;

impl Guest for Component {
    fn tick(state: VehicleState, sp: RateSetpoint) -> TorqueSetpoint {
        let torque = PID.0.borrow_mut().tick(
            next_timestamp(),
            [state.wx, state.wy, state.wz],
            [sp.rx, sp.ry, sp.rz],
        );
        TorqueSetpoint {
            tx: torque[0],
            ty: torque[1],
            tz: torque[2],
            // Thrust passes straight through the rate loop.
            thrust: sp.thrust,
        }
    }
}

bindings::export!(Component with_types_in bindings);

// no_std (cargo-component path) needs a panic handler; the Bazel path (std)
// provides its own.
#[cfg(not(feature = "bazel-bindings"))]
#[panic_handler]
fn panic(_: &core::panic::PanicInfo) -> ! {
    loop {}
}
