//! falcon-mixer — the X-config quad mixer as a Component Model
//! component. Wraps `relay-mix-quad::QuadMixer`.
//!
//! v0.7: exports the `pulseengine:falcon-cascade/mixer` interface. `wac` wires
//! this component's export into the `cascade` orchestrator's import
//! (see falcon-cascade.wac). The mixer is stateless per call, so the
//! `Guest` impl just constructs a `QuadMixer` and runs one `mix`.

#![cfg_attr(not(feature = "std"), no_std)]

// Bounded work-memory arena + the canonical-ABI `cabi_realloc` export + a panic
// handler, from the shared crate so the `unsafe` lives in one audited place.
// no_std keeps the component free of WASI and of `memory.grow`, which is what
// blocks `meld fuse --memory shared --address-rebase` (gale#89, meld#299).
#[cfg(not(feature = "std"))]
falcon_cm_rt::export_cm_rt!();

// Bindings generated by cargo-component as src/bindings.rs.
#[allow(warnings)]
#[cfg(feature = "bazel-bindings")]
use falcon_mixer_bindings as bindings;
#[cfg(not(feature = "bazel-bindings"))]
mod bindings;

use bindings::exports::pulseengine::falcon_cascade::mixer::Guest;
use bindings::pulseengine::falcon_cascade::types::{MotorPwm, TorqueSetpoint};

use relay_mix_quad::QuadMixer;

struct Component;

impl Guest for Component {
    fn mix(torque: TorqueSetpoint) -> MotorPwm {
        let mut mixer = QuadMixer::new();
        let m = mixer.mix([torque.tx, torque.ty, torque.tz], torque.thrust);
        MotorPwm {
            m1: m[0],
            m2: m[1],
            m3: m[2],
            m4: m[3],
        }
    }
}

bindings::export!(Component with_types_in bindings);
