//! falcon-mixer — the X-config quad mixer as a Component Model
//! component. Wraps `relay-mix-quad::QuadMixer`.
//!
//! v0.7: exports the `falcon:cascade/mixer` interface. `wac` wires
//! this component's export into the `cascade` orchestrator's import
//! (see falcon-cascade.wac). The mixer is stateless per call, so the
//! `Guest` impl just constructs a `QuadMixer` and runs one `mix`.

// Bindings generated by cargo-component as src/bindings.rs.
#[allow(warnings)]
#[cfg(feature = "bazel-bindings")]
use falcon_mixer_bindings as bindings;
#[cfg(not(feature = "bazel-bindings"))]
mod bindings;

use bindings::exports::falcon::cascade::mixer::Guest;
use bindings::falcon::cascade::types::{MotorPwm, TorqueSetpoint};

use relay_mix_quad::QuadMixer;

struct Component;

impl Guest for Component {
    fn mix(torque: TorqueSetpoint) -> MotorPwm {
        let mut mixer = QuadMixer::new();
        let m = mixer.mix([torque.tx, torque.ty, torque.tz], torque.thrust);
        MotorPwm {
            m1: m[0],
            m2: m[1],
            m3: m[2],
            m4: m[3],
        }
    }
}

bindings::export!(Component with_types_in bindings);
