//! falcon-ekf — the Mahony attitude estimator as a Component Model
//! component. Wraps `relay-ekf::Ekf`.
//!
//! Stateful: the `Ekf` (quaternion + gyro-bias integrator) persists
//! across `estimate` calls in a component-instance-local cell.
//! Timestamps are synthesised as a 1 kHz monotonic counter.

#![cfg_attr(not(feature = "std"), no_std)]

// Bounded work-memory arena + `cabi_realloc` + panic handler from the shared
// crate (crates/falcon-cm-rt), so the unsafe lives in one audited place.
#[cfg(not(feature = "std"))]
falcon_cm_rt::export_cm_rt!();

// Bindings are generated by cargo-component as src/bindings.rs.
#[allow(warnings)]
#[cfg(feature = "bazel-bindings")]
use falcon_ekf_bindings as bindings;
#[cfg(not(feature = "bazel-bindings"))]
mod bindings;

use core::cell::RefCell;

struct SingleThreaded<T>(RefCell<T>);
// SAFETY: the component model guarantees single-threaded, non-reentrant access.
unsafe impl<T> Sync for SingleThreaded<T> {}

use bindings::exports::pulseengine::falcon_cascade::ekf::Guest;
use bindings::pulseengine::falcon_cascade::types::{SensorFrame, VehicleState};

use relay_ekf::{Ekf, ImuSample as RImu, Timestamp};

static EKF: SingleThreaded<Ekf> = SingleThreaded(RefCell::new(Ekf::new()));
/// Monotonic nanosecond counter, advanced by the HOST's period.
///
/// v0.7 advanced this by exactly 1 ms per call — "the cascade runs at 1 kHz" —
/// which is the same defect the iekf component carried: a host ticking at any
/// other rate got a timeline that ran fast or slow, silently. Nanoseconds
/// rather than milliseconds because a 250 Hz host is 4 ms and a 400 Hz host is
/// 2.5 ms; integer-millisecond accumulation truncates the latter to 2 ms and
/// drifts 20% per tick.
static TICK_NS: SingleThreaded<u64> = SingleThreaded(RefCell::new(0));

fn advance_timestamp(dt_s: f32) -> Timestamp {
    // Same clamp as the iekf component: [0.1 ms, 100 ms], non-finite falls back
    // to the v0.7 constant.
    let dt = if dt_s.is_finite() { dt_s.clamp(0.0001, 0.1) } else { 0.001 };
    let ns = *TICK_NS.0.borrow();
    *TICK_NS.0.borrow_mut() = ns + (dt as f64 * 1e9) as u64;
    Timestamp {
        seconds: ns / 1_000_000_000,
        fraction: (((ns % 1_000_000_000) as u128 * (1u128 << 32)) / 1_000_000_000) as u32,
    }
}

struct Component;

impl Guest for Component {
    fn estimate(sensors: SensorFrame) -> VehicleState {
        let imu = sensors.imu;
        let sample = RImu {
            time: advance_timestamp(sensors.dt_s),
            accel_body: [imu.ax, imu.ay, imu.az],
            gyro_body: [imu.gx, imu.gy, imu.gz],
        };
        let st = EKF.0.borrow_mut().tick(sample);
        VehicleState {
            qw: st.quaternion[0],
            qx: st.quaternion[1],
            qy: st.quaternion[2],
            qz: st.quaternion[3],
            pos_n: st.position_ned[0],
            pos_e: st.position_ned[1],
            pos_d: st.position_ned[2],
            vel_n: st.velocity_ned[0],
            vel_e: st.velocity_ned[1],
            vel_d: st.velocity_ned[2],
            // Body rates are the gyro reading, passed through for the
            // rate loop (the Mahony filter does not re-estimate them).
            wx: imu.gx,
            wy: imu.gy,
            wz: imu.gz,
            innovation: st.innovation,
        }
    }
}

bindings::export!(Component with_types_in bindings);
