//! falcon-ekf — the Mahony attitude estimator as a Component Model
//! component. Wraps `relay-ekf::Ekf`.
//!
//! Stateful: the `Ekf` (quaternion + gyro-bias integrator) persists
//! across `estimate` calls in a component-instance-local cell.
//! Timestamps are synthesised as a 1 kHz monotonic counter.

// Bindings are generated by cargo-component as src/bindings.rs.
#[allow(warnings)]
#[cfg(feature = "bazel-bindings")]
use falcon_ekf_bindings as bindings;
#[cfg(not(feature = "bazel-bindings"))]
mod bindings;

use core::cell::RefCell;

use bindings::exports::falcon::cascade::ekf::Guest;
use bindings::falcon::cascade::types::{ImuSample, VehicleState};

use relay_ekf::{Ekf, ImuSample as RImu, Timestamp};

thread_local! {
    static EKF: RefCell<Ekf> = RefCell::new(Ekf::new());
    /// Monotonic millisecond counter — the cascade runs at 1 kHz.
    static TICK_MS: RefCell<u64> = const { RefCell::new(0) };
}

fn next_timestamp() -> Timestamp {
    TICK_MS.with(|c| {
        let ms = *c.borrow();
        *c.borrow_mut() = ms + 1;
        Timestamp {
            seconds: ms / 1000,
            fraction: ((ms % 1000) * (1u64 << 32) / 1000) as u32,
        }
    })
}

struct Component;

impl Guest for Component {
    fn estimate(imu: ImuSample) -> VehicleState {
        let sample = RImu {
            time: next_timestamp(),
            accel_body: [imu.ax, imu.ay, imu.az],
            gyro_body: [imu.gx, imu.gy, imu.gz],
        };
        let st = EKF.with(|e| e.borrow_mut().tick(sample));
        VehicleState {
            qw: st.quaternion[0],
            qx: st.quaternion[1],
            qy: st.quaternion[2],
            qz: st.quaternion[3],
            pos_n: st.position_ned[0],
            pos_e: st.position_ned[1],
            pos_d: st.position_ned[2],
            vel_n: st.velocity_ned[0],
            vel_e: st.velocity_ned[1],
            vel_d: st.velocity_ned[2],
            // Body rates are the gyro reading, passed through for the
            // rate loop (the Mahony filter does not re-estimate them).
            wx: imu.gx,
            wy: imu.gy,
            wz: imu.gz,
            innovation: st.innovation,
        }
    }
}

bindings::export!(Component with_types_in bindings);
